sonar.projectKey=Fouriers_Continuum_Experience
sonar.projectName=Fouriers Continuum Experience
sonar.projectVersion=1.0

sonar.modules=backend,frontend

backend.sonar.projectName=FCE-Backend
backend.sonar.projectBaseDir=Back-End
backend.sonar.sources=src/main/java
backend.sonar.tests=src/test/java
backend.sonar.java.binaries=target/classes
backend.sonar.java.source=1.8

frontend.sonar.projectName=FCE-Frontend
frontend.sonar.projectBaseDir=Front-End
frontend.sonar.sources=src
frontend.sonar.exclusions=/node_modules/,*/.spec.ts