pipeline {
    agent any

    tools {
        maven 'Maven_Jenkins'
        jdk 'Default JDK'
        nodejs 'NodeJS-Angular'
    }

    stages {

        stage('SCM') {
            steps {
                checkout scm
            }
        }

        stage('Debug Backend Structure') {
            steps {
                sh 'ls -la'
                dir('Back-End') {
                    sh 'ls -la'
                }
            }
        }

        stage('SonarQube Backend') {
            steps {
                dir('Back-End') {
                    withSonarQubeEnv('sonarqube') {
                        sh 'mvn clean verify sonar:sonar'
                    }
                }
            }
        }

        stage('Build Backend') {
            steps {
                dir('Back-End') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test Backend') {
            steps {
                dir('Back-End') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('Front-End') {
                    nodejs(nodeJSInstallationName: 'NodeJS-Angular') {
                        sh 'npm install'
                        sh 'npm run build'
                    }
                }
            }
        }
        
        stage('Test Frontend') {
            steps {
                dir('Front-End') {
                    nodejs(nodeJSInstallationName: 'NodeJS-Angular') {
                        sh 'npm test || true'
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarScanner'
                    withSonarQubeEnv('sonarqube') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }
    }
}
